### ISSUE TITLE
Upload module not work

### ISSUE THREAD

**Issue by enri90** [crypto-com/crypto-pay-prestashop#2]
Module not valid for install on prestashop v1.7.7.0

**Comment by v1per4llbl4ck** [comment]
me too i cant upload module... not work also manually

**Comment by thomasmktong-cryptocom** [comment]
Hi @enri90 and @v1per4llbl4ck, thanks for reporting this issue. We found 2 causes that can potentially lead to this problem. Please let us know whether the following solves it. If not, we are happy to help further.

## 1 - Your store does not have EUR or USD currencies set up

Apologies that this is a misconfiguration of our plugin in our first release. The problem has been fixed in v1.0.1.

## 2 - You uploaded a zip package of the source code instead of using the Release package in [Release page](https://github.com/crypto-com/crypto-pay-prestashop/releases)

The content of the plugin has to be located under a folder called `cryptopay` in the plugin zip package. If you tried to zip the source code and upload to PrestaShop backend, then the error will be reported. Please make sure you upload the Release package downloaded from the [Release page](https://github.com/crypto-com/crypto-pay-prestashop/releases).

![image](https://user-images.githubusercontent.com/71475484/114350928-78462b00-9b9c-11eb-9974-aec01be1e07a.png)

**Comment by enri90** [comment]
successful installation Thank you!
but when testing the payment I see this message!

[response](https://user-images.githubusercontent.com/2630335/114471546-1ebc1b80-9bf1-11eb-9a03-5b9e6b5397cb.png)

**Comment by thomasmktong-cryptocom** [comment]
Have you put in the correct API keys in the addon settings? You may refer to [this FAQ page](https://help.crypto.com/en/articles/4732840-prestashop-setup-guide?utm_source=Prestashop&utm_medium=Website&utm_campaign=Pay%20Merchant) for the setup instructions. If it still does not work you may send a email to pay@crypto.com with the website of your store and we can help to take a look. Thanks.

**Comment by enri90** [comment]
yes I have saved the keys in the settings
where can i find the log file?

in the image as you see it remains empty after saving

![save](https://user-images.githubusercontent.com/2630335/114472636-e4537e00-9bf2-11eb-95f4-4f10d09bb0fc.png)

**Comment by v1per4llbl4ck** [comment]
For me in test work all good!

Thanks!

Alberto Galassi

Founder of Agws.it | Ecommerce and product Manager 


Tel/Whattsapp +39 392 73 46 609

***@***.***

www.agws.it

**Comment by enri90** [comment]
> For me in test work all good! Thanks! Alberto Galassi Founder of Agws.it | Ecommerce and product Manager Tel/Whattsapp +39 392 73 46 609 ***@***.*** [www.agws.it](http://www.agws.it)
> […](#)
> Il giorno 13 apr 2021, alle ore 00:55, enri90 ***@***.***> ha scritto: ﻿ yes I have saved the keys in the settings where can i find the log file? in the image as you see it remains empty after saving — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

what version of prestashop are you using?

**Comment by thomasmktong-cryptocom** [comment]
Close as resolved.
